// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogQK813Khe1Kt5ZoblKUma_AMf252zLo',
    appId: '1:847200190687:web:e7810f0968c2880b23e96a',
    messagingSenderId: '847200190687',
    projectId: 'smart-energy-meter-266d8',
    authDomain: 'smart-energy-meter-266d8.firebaseapp.com',
    databaseURL: 'https://smart-energy-meter-266d8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-energy-meter-266d8.firebasestorage.app',
    measurementId: 'G-B9QXHEKLLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpjZaiSmuDNKVoU1P_zeMrG9HxjMtC0xg',
    appId: '1:847200190687:android:f528994de9dadd7823e96a',
    messagingSenderId: '847200190687',
    projectId: 'smart-energy-meter-266d8',
    databaseURL: 'https://smart-energy-meter-266d8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-energy-meter-266d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzJ2Ov6n1oYuM-CGfPMPzaeNqsoUcBr0',
    appId: '1:847200190687:ios:1b3542ad7671b7ca23e96a',
    messagingSenderId: '847200190687',
    projectId: 'smart-energy-meter-266d8',
    databaseURL: 'https://smart-energy-meter-266d8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-energy-meter-266d8.firebasestorage.app',
    iosBundleId: 'com.example.smartEnergyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdzJ2Ov6n1oYuM-CGfPMPzaeNqsoUcBr0',
    appId: '1:847200190687:ios:1b3542ad7671b7ca23e96a',
    messagingSenderId: '847200190687',
    projectId: 'smart-energy-meter-266d8',
    databaseURL: 'https://smart-energy-meter-266d8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-energy-meter-266d8.firebasestorage.app',
    iosBundleId: 'com.example.smartEnergyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAogQK813Khe1Kt5ZoblKUma_AMf252zLo',
    appId: '1:847200190687:web:512aa119070b0fe423e96a',
    messagingSenderId: '847200190687',
    projectId: 'smart-energy-meter-266d8',
    authDomain: 'smart-energy-meter-266d8.firebaseapp.com',
    databaseURL: 'https://smart-energy-meter-266d8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-energy-meter-266d8.firebasestorage.app',
    measurementId: 'G-5WYJNNKCZC',
  );
}
